### ISSUE TITLE
File and Folder selection screens don't allow the drive to be changed on Windows

### ISSUE THREAD

**Issue by henderjj** [davidblackuk/MountFuji#10]
The file and folder selection screens only allow the C drive to be browsed. I'm unable to select the Hatari exe if Hatari is installed on E.

**Comment by davidblackuk** [comment]
Move the file picker to a three column model

**Comment by davidblackuk** [comment]
A fix for this will be in the 1.03 release, it is now in the main branch

**Comment by davidblackuk** [comment]
This was addressed in change set #12, and published in release 1.0.3 @henderjj , any chance you could download and verify?

**Comment by henderjj** [comment]
> This was addressed in change set #12, and published in release 1.0.3 @henderjj , any chance you could download and verify?

Yes, that all works. I can select files and folders on the E: drive now. Thanks!
