### ISSUE TITLE
Windows - Radio Buttons look disabled in dark mode

### ISSUE THREAD

**Issue by davidblackuk** [davidblackuk/MountFuji#18]
In windows when using dark mode, the radio buttons look disabled, the main part of the button, the circle and the selection indicator appear as black, which on a darkmode background isn't exactly appealing.

We need to work out a way of styling the radio button similarly to MacOS

**Comment by henderjj** [comment]
FYI. The radio buttons look fine for me in dark mode:

![image](https://github.com/davidblackuk/MountFuji/assets/13685295/9c65f495-d240-4147-8ad7-878cf0646711)

However, in light mode, they're really hard to see:

![image](https://github.com/davidblackuk/MountFuji/assets/13685295/bd68a709-5a2d-4446-af61-9efa47456d1c)

It might be dependent on the Windows dark mode setting (I've got Dark mode enabled).
