### ISSUE TITLE
Create a general OK / Cancel control

### ISSUE THREAD

**Issue by davidblackuk** [davidblackuk/MountFuji#20]
Currently the OK and Cancel buttons live in each dialog. I'd like to abstract them into a custom control
that allows Fuji to order them 

[Cancel] [OK]

on Mac, and

[OK] [Cancel]

On Windows

This could be as easy as two groups of two buttons using the same two commands, with a group enabled or disabled based on platform.

**Comment by hunsra** [comment]
@davidblackuk, I can take this one.

**Comment by hunsra** [comment]
Try this commit out and let me know if this is what you were after.

**Comment by davidblackuk** [comment]
closed this as complete, thanks Randy, awesome stuff. created #25 to see if we can remove boiler plate code, though #19 may be a better next step as it adds more value
